default['git-server']['source-dir'] = '/etc/git-server'
default['git-server']['server-dir'] = '/var/www/bookstore'
default['secret_key_file_location'] = '/etc/.keys.yml'
default['elasticsearch']['data_path'] = '/home/deployer/elasticsearch'
default['haproxy']['backend_fqdn'] = 'backend.ez-items.com'
